# Generated by Django 5.2.1 on 2025-05-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WidowProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('spouse_name', models.CharField(max_length=100)),
                ('cause_of_death', models.CharField(max_length=200)),
                ('nationality', models.CharField(choices=[('Indian', 'Indian')], default='Indian', max_length=50)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Muslim', 'Muslim')], max_length=50)),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(max_length=15)),
                ('case_history', models.TextField()),
                ('dependents', models.TextField()),
                ('death_certificate', models.BooleanField(default=False)),
                ('aadhar_card', models.BooleanField(default=False)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('letter_from_sarpanch', models.BooleanField(default=False)),
                ('emergency_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
