# Generated by Django 5.2.1 on 2025-05-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_widowprofile_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='widowprofile',
            table='ngo_data',
        ),
    ]
