# Generated by Django 5.1.1 on 2025-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_widowprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='widowprofile',
            name='dependents_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='widowprofile',
            name='dependents_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='widowprofile',
            name='dependents_sex',
            field=models.CharField(default='', max_length=50),
        ),
    ]
