# Generated by Django 5.1.1 on 2025-06-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_widowprofile_dependents_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widowprofile',
            name='dependents_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='widowprofile',
            name='dependents_sex',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
