# Generated by Django 5.1.1 on 2025-06-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_widowprofile_dependents_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widowprofile',
            name='aadhar_card_file',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_cards/'),
        ),
        migrations.AddField(
            model_name='widowprofile',
            name='death_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='death_certificates/'),
        ),
        migrations.AlterField(
            model_name='widowprofile',
            name='dependents',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
