# Generated by Django 5.1.1 on 2025-06-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_widowprofile_aadhar_card_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widowprofile',
            name='application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widowprofile',
            name='application_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
    ]
