# Generated by Django 5.1.1 on 2025-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_widowprofile_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widowprofile',
            name='project_name',
            field=models.CharField(blank=True, choices=[('TCA CUTTACK', 'TCA CUTTACK'), ('TCA BHUBANESWAR', 'TCA BHUBANESWAR'), ('TCA SUNDARGARH', 'TCA SUNDARGARH'), ('TCA PARALAKHEMUNDI', 'TCA PARALAKHEMUNDI'), ('TCA CHANDIGARH', 'TCA CHANDIGARH'), ('TCA GUNTUR(A)', 'TCA GUNTUR(A)'), ('TCA GUNTUR(B)', 'TCA GUNTUR(B)'), ('TCA EAST GODAVARI(A)', 'TCA EAST GODAVARI(A)'), ('TCA EAST GODAVARI(B)', 'TCA EAST GODAVARI(B)'), ('TCA MOHANA', 'TCA MOHANA')], max_length=100, null=True),
        ),
    ]
